src/Entity/Enigma.php
<?php

namespace App\Entity;

use App\Repository\EnigmaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EnigmaRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Enigma
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message = "La question ne doit pas être vide")
     */
    private $question;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message = "L'ordre de la question doit être renseigné")
     * @Assert\Type(
     *     type="integer",
     *     message="La valeur {{ value }} n'est pas de type {{ type }}."
     * )
     * @Assert\Positive(message = "L'ordre de la question doit être un chiffre positif")
     */
    private $orderEnigma;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\NotBlank(message = "La date de création de la question doit être renseignée")
     * @Assert\Type(type="\DateTimeInterface", message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Assert\Type(type="\DateTimeInterface", message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Checkpoint::class, inversedBy="enigmas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $checkpoint;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="enigma")
     */
    private $answers;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\Type(
     *     type="bool",
     *     message="La valeur {{ value }} n'est pas du type : {{ type }}."
     * )
     */
    private $isTrashed;

    /**
     * @ORM\OneToMany(targetEntity=UserAnswer::class, mappedBy="enigma")
     */
    private $userAnswers;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
        $this->isTrashed = false;
        $this->userAnswers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getOrderEnigma(): ?int
    {
        return $this->orderEnigma;
    }

    public function setOrderEnigma(int $orderEnigma): self
    {
        $this->orderEnigma = $orderEnigma;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCheckpoint(): ?Checkpoint
    {
        return $this->checkpoint;
    }

    public function setCheckpoint(?Checkpoint $checkpoint): self
    {
        $this->checkpoint = $checkpoint;

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getUnTrashedAnswers(): Collection
    {
        $criteria = Criteria::create()
        ->andWhere(Criteria::expr()->eq('isTrashed', false));
        return $this->answers->matching($criteria);
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setEnigma($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getEnigma() === $this) {
                $answer->setEnigma(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getIsTrashed(): ?bool
    {
        return $this->isTrashed;
    }

    public function setIsTrashed(bool $isTrashed): self
    {
        $this->isTrashed = $isTrashed;

        return $this;
    }

    /**
     * @return Collection<int, UserAnswer>
     */
    public function getUserAnswers(): Collection
    {
        return $this->userAnswers;
    }

    public function addUserAnswer(UserAnswer $userAnswer): self
    {
        if (!$this->userAnswers->contains($userAnswer)) {
            $this->userAnswers[] = $userAnswer;
            $userAnswer->setEnigma($this);
        }

        return $this;
    }

    public function removeUserAnswer(UserAnswer $userAnswer): self
    {
        if ($this->userAnswers->removeElement($userAnswer)) {
            // set the owning side to null (unless already changed)
            if ($userAnswer->getEnigma() === $this) {
                $userAnswer->setEnigma(null);
            }
        }

        return $this;
    }
}

src/Form/EnigmaType.php
<?php

namespace App\Form;

use App\Entity\Enigma;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnigmaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('question', TextareaType::class,[
                'label' => 'Votre énigme:',
                'attr' => ['placeholder' => 'Quel est la couleur du cheval blanc de Henry IV ?'],
            ])
            ->add('orderEnigma', NumberType::class,[
                'label' => 'Ordre de l\' énigme :',
                'html5' => true,
                // TODO The 3 next line need to be delete if we have more than 1 enigma
                'data' => 1,
                'attr' => ['style' => 'display:none'],
                'label_attr' => ['style' => 'display:none'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Enigma::class,
        ]);
    }
}

src/Controller/Backoffice/AnswerController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\Answer;
use App\Entity\Enigma;
use App\Form\AnswerType;
use App\Repository\AnswerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @Route("/backoffice/answer", name="app_backoffice_answer_")
 */
class AnswerController extends AbstractController
{
    private $breadcrumb;
    private $urlGenerator;

    public function __construct(UrlGeneratorInterface $urlGenerator)
    {
        $this->urlGenerator = $urlGenerator;
        $this->breadcrumb = array(array('libelle' => 'Jeux', 'libelle_url' => 'app_backoffice_game_index', 'url' => $this->urlGenerator->generate('app_backoffice_game_index')));
    }

    /**
     * @Route("/enigme/{id}/nouveau", name="new", methods={"GET", "POST"}, requirements={"id"="\d+"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, Enigma $enigma): Response
    {
        $answer = new Answer();
        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $answer->setEnigma($enigma);
            $entityManager->persist($answer);
            $entityManager->flush();

            $this->addFlash(
                'notice-success',
                'La réponse '.$answer->getAnswer().' a été créée !'
            );

            return $this->redirectToRoute('app_backoffice_enigma_show', ['id' => $enigma->getId()], Response::HTTP_SEE_OTHER);
        }

        array_push($this->breadcrumb, array('libelle' => $enigma->getCheckpoint()->getGame()->getTitle(), 'libelle_url' => 'app_backoffice_game_show', 'url' => $this->urlGenerator->generate('app_backoffice_game_show', ['slug' => $enigma->getCheckpoint()->getGame()->getSlug()])));

        array_push($this->breadcrumb, array('libelle' => $enigma->getCheckpoint()->getTitle(), 'libelle_url' => 'app_backoffice_checkpoint_show', 'url' => $this->urlGenerator->generate('app_backoffice_checkpoint_show', ['id' => $enigma->getCheckpoint()->getId()])));

        array_push($this->breadcrumb, array('libelle' => 'Enigme'.$enigma->getOrderEnigma(), 'libelle_url' => 'app_backoffice_enigma_show', 'url' => $this->urlGenerator->generate('app_backoffice_enigma_show', ['id' => $enigma->getId()])));

        array_push($this->breadcrumb, array('libelle' => 'Nouvelle réponse', 'libelle_url' => 'app_backoffice_answer_new', 'url' => $this->urlGenerator->generate('app_backoffice_answer_new', ['id' => $enigma->getId()])));

        return $this->renderForm('backoffice/answer/new.html.twig', [
            'answer' => $answer,
            'form' => $form,
            'enigma' => $enigma,
            'breadcrumbs' => $this->breadcrumb,
        ]);
    }

    /**
     * @Route("/{id}/modifier", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     */
    public function edit(Request $request, Answer $answer, EntityManagerInterface $entityManager): Response
    {
        // Organizer or Admin can modify this game
        $this->denyAccessUnlessGranted('IS_MY_GAME', $answer);

        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $this->addFlash(
                'notice-success',
                'La réponse '.$answer->getAnswer().' a été modifiée !'
            );

            return $this->redirectToRoute('app_backoffice_enigma_show', ['id' => $answer->getEnigma()->getId()], Response::HTTP_SEE_OTHER);
        }

        array_push($this->breadcrumb, array('libelle' => $answer->getEnigma()->getCheckpoint()->getGame()->getTitle(), 'libelle_url' => 'app_backoffice_game_show', 'url' => $this->urlGenerator->generate('app_backoffice_game_show', ['slug' => $answer->getEnigma()->getCheckpoint()->getGame()->getSlug()])));

        array_push($this->breadcrumb, array('libelle' => $answer->getEnigma()->getCheckpoint()->getTitle(), 'libelle_url' => 'app_backoffice_checkpoint_show', 'url' => $this->urlGenerator->generate('app_backoffice_checkpoint_show', ['id' => $answer->getEnigma()->getCheckpoint()->getId()])));

        array_push($this->breadcrumb, array('libelle' => 'Enigme '.$answer->getEnigma()->getOrderEnigma(), 'libelle_url' => 'app_backoffice_enigma_index', 'url' => $this->urlGenerator->generate('app_backoffice_enigma_show', ['id' => $answer->getEnigma()->getId()])));

        array_push($this->breadcrumb, array('libelle' => 'Réponse : '.$answer->getAnswer(), 'libelle_url' => 'app_backoffice_answer_edit', 'url' => $this->urlGenerator->generate('app_backoffice_answer_edit', ['id' => $answer->getId()])));

        return $this->renderForm('backoffice/answer/edit.html.twig', [
            'answer' => $answer,
            'form' => $form,
            'breadcrumbs' => $this->breadcrumb,
        ]);
    }

    /**
     * @Route("/{id}", name="trash", methods={"POST"}, requirements={"id"="\d+"})
     */
    public function trash(Request $request, Answer $answer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('trash'.$answer->getId(), $request->request->get('_token')))
        {
            $answer->setIsTrashed(true);
            $this->addFlash(
                'notice-success',
                'La réponse '.$answer->getAnswer().' a été supprimée !'
            );
            $entityManager->flush();
        }
        else
        {
            $this->addFlash(
                'notice-danger',
                'Impossible de supprimer la réponse '.$answer->getAnswer().', token invalide !'
            );
        }

        return $this->redirectToRoute('app_backoffice_enigma_show', ['id' => $answer->getEnigma()->getId()], Response::HTTP_SEE_OTHER);
    }
}

templates/backoffice/enigma/_delete_form.html.twig
<form method="post" action="{{ path('app_backoffice_enigma_trash', {'id': enigma.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette énigme ? Cette énigme sera mit à la poubelle !');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enigma.id) }}">
    <button class="btn btn-danger btn-sm me-3">Supprimer</button>
</form>

templates/backoffice/enigma/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/backoffice/enigma/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'énigme du checkpoint{{checkpoint.title}}{% endblock %}

{% block body %}
    {{ include('_header_start.html.twig', {'title': 'Edition de l\'énigme '~enigma.orderEnigma }) }}

    <div class="container-xxl pb-5">
        <div class="container">
            <div class="d-flex flex-row-reverse bd-highlight align-items-start">
                <a href="{{ path('app_backoffice_checkpoint_show', {'id': checkpoint.id}) }}" class="btn btn-outline-secondary btn-sm">Retourner au checkpoint</a>
            </div> 

            {{ include('backoffice/enigma/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        </div>
    </div>
{% endblock %}

templates/backoffice/enigma/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle énigme pour le checkpoint {{ checkpoint.title }}{% endblock %}

{% block body %}
    {{ include('_header_start.html.twig', {'title': 'Nouvelle énigme' }) }}

    <div class="container-xxl pb-5">
        <div class="container">
            <div class="d-flex flex-row-reverse bd-highlight align-items-start">
                <a href="{{ path('app_backoffice_checkpoint_show', {'id': checkpoint.id}) }}" class="btn btn-outline-secondary btn-sm">Retourner au checkpoint</a>
            </div>

            {{ include('backoffice/enigma/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/backoffice/enigma/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enigme {{ enigma.orderEnigma }} du checkpoint {{ enigma.checkpoint.title }}{% endblock %}

{% block body %}

{{ include('_header_start.html.twig', {'title': 'Enigme '~enigma.orderEnigma }) }}

<div class="container-xxl pb-5">
    <div class="container">
        <div class="d-flex flex-row-reverse bd-highlight align-items-start">
            <a href="{{ path('app_backoffice_checkpoint_show', {'id': enigma.checkpoint.id }) }}" class="btn btn-outline-secondary btn-sm">Retourner au checkpoint</a>
            {{ include('backoffice/enigma/_delete_form.html.twig') }}
            <a href="{{ path('app_backoffice_enigma_edit', {'id': enigma.id}) }}" class="btn btn-primary btn-sm me-3">Modifier</a>
        </div>

        <table class="table">
            <tbody>

                <tr>
                    <th>Enigme</th>
                    <td>{{ enigma.question }}</td>
                </tr>
                <tr>
                    <th>Ordre de l'énigme</th>
                    <td>{{ enigma.orderEnigma }}</td>
                </tr>
                <tr>
                    <th>Créée le</th>
                    <td>{{ enigma.createdAt ? enigma.createdAt|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Modifié le</th>
                    <td>{{ enigma.updatedAt ? enigma.updatedAt|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
            </tbody>
        </table>

        <div id="answers-cards-ic" class="d-flex bd-highlight">
            <div class="card mb-3 flex-grow-1" style="flex-basis:min-content;" >
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <h2 class="p-2 align-self-center flex-grow-1">Les réponses</h2>
                    <a class="btn btn-primary m-3" href="{{ path('app_backoffice_answer_new', {'id': enigma.id}) }}">Créer une réponse</a>
                </div>
                <div class="accordion" id="ac-answers">
                    {% for answer in enigma.unTrashedAnswers %}
                        
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="instance-head-{{loop.index}}">
                                <button class="accordion-button text-white bg-gradient 
                                {% if answer.status %}
                                    bg-success 
                                {% else %}
                                    bg-warning
                                {% endif %}
                                    collapsed" 
                                type="button" data-bs-toggle="collapse" data-bs-target="#answers-{{loop.index}}" 
                                aria-expanded="false" 
                                aria-controls="answers-{{loop.index}}">
                                    Réponse {{answer.answer}} 
                                        ({% if answer.status %}
                                            La bonne réponse
                                        {% else %}
                                            Une mauvaise réponse
                                        {% endif %})
                                </button>
                            </h2>
                            <div id="answers-{{loop.index}}" class="accordion-collapse collapse" aria-labelledby="answer-head-{{loop.index}}" data-bs-parent="#ac-answers">
                                <div class="accordion-body">
                                    <div class="mb-3">
                                        <strong>{{answer.answer}}</strong>
                                    </div>
                                    <div class="d-flex bd-highlight align-items-start">
                                        <a href="{{ path('app_backoffice_answer_edit',{'id': answer.id}) }}" class="btn btn-warning btn-sm me-3">Modifier</a>
                                        {{ include('backoffice/answer/_delete_form.html.twig') }}
                                    </div>
                                </div>
                            </div>
                        </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}