src/Entity/Checkpoint.php
<?php

namespace App\Entity;

use App\Repository\CheckpointRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Game;
use Doctrine\Common\Collections\Criteria;

/**
 * @ORM\Entity(repositoryClass=CheckpointRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Checkpoint
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message = "Le titre du checkpoint ne doit pas être vide")
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Le titre du checkpoint doit au minimum faire {{ limit }} caractères !",
     *      maxMessage = "Le titre du checkpoint ne doit pas éxéder {{ limit }} caractères !"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message = "Le message de succés du checkpoint ne doit pas être vide")
     */
    private $successMessage;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message = "L'ordre du checkpoint doit être renseigné")
     * @Assert\Type(
     *     type="integer",
     *     message="La valeur {{ value }} n'est pas de type {{ type }}."
     * )
     * @Assert\Positive(message = "L'ordre du checkpoint doit être un chiffre positif")
     */
    private $orderCheckpoint;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\NotBlank(message = "La date de création du checkpoint doit être renseignée")
     * @Assert\Type(type="\DateTimeInterface", message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Assert\Type(type="\DateTimeInterface", message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Game::class, inversedBy="checkpoints")
     * @ORM\JoinColumn(nullable=false)
     */
    private $game;

    /**
     * @ORM\OneToMany(targetEntity=ScanQR::class, mappedBy="checkpoint")
     */
    private $scanQRs;

    /**
     * @ORM\OneToMany(targetEntity=Enigma::class, mappedBy="checkpoint")
     * @ORM\OrderBy({"orderEnigma" = "ASC"})
     */
    private $enigmas;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\Type(
     *     type="bool",
     *     message="La valeur {{ value }} n'est pas du type : {{ type }}."
     * )
     */
    private $isTrashed;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $success_image;

    public function __construct()
    {
        $this->scanQRs = new ArrayCollection();
        $this->enigmas = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
        $this->isTrashed = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSuccessMessage(): ?string
    {
        return $this->successMessage;
    }

    public function setSuccessMessage(string $successMessage): self
    {
        $this->successMessage = $successMessage;

        return $this;
    }

    public function getOrderCheckpoint(): ?int
    {
        return $this->orderCheckpoint;
    }

    public function setOrderCheckpoint(int $orderCheckpoint): self
    {
        $this->orderCheckpoint = $orderCheckpoint;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): self
    {
        $this->game = $game;

        return $this;
    }

    /**
     * @return Collection<int, ScanQR>
     */
    public function getScanQRs(): Collection
    {
        return $this->scanQRs;
    }

    public function addScanQR(ScanQR $scanQR): self
    {
        if (!$this->scanQRs->contains($scanQR)) {
            $this->scanQRs[] = $scanQR;
            $scanQR->setCheckpoint($this);
        }

        return $this;
    }

    public function removeScanQR(ScanQR $scanQR): self
    {
        if ($this->scanQRs->removeElement($scanQR)) {
            // set the owning side to null (unless already changed)
            if ($scanQR->getCheckpoint() === $this) {
                $scanQR->setCheckpoint(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Enigma>
     */
    public function getEnigmas(): Collection
    {
        return $this->enigmas;
    }

    /**
     * @return Collection<int, Enigma>
     */
    public function getUnTrashedEnigmas(): Collection
    {
        $criteria = Criteria::create()
        ->andWhere(Criteria::expr()->eq('isTrashed', false));
        return $this->enigmas->matching($criteria);
    }

    public function addEnigma(Enigma $enigma): self
    {
        if (!$this->enigmas->contains($enigma)) {
            $this->enigmas[] = $enigma;
            $enigma->setCheckpoint($this);
        }

        return $this;
    }

    public function removeEnigma(Enigma $enigma): self
    {
        if ($this->enigmas->removeElement($enigma)) {
            // set the owning side to null (unless already changed)
            if ($enigma->getCheckpoint() === $this) {
                $enigma->setCheckpoint(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getIsTrashed(): ?bool
    {
        return $this->isTrashed;
    }

    public function setIsTrashed(bool $isTrashed): self
    {
        $this->isTrashed = $isTrashed;

        return $this;
    }

    public function getSuccessImage(): ?string
    {
        return $this->success_image;
    }

    public function setSuccessImage(?string $success_image): self
    {
        $this->success_image = $success_image;

        return $this;
    }
}

src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=GameRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message = "Le titre du jeu ne doit pas être vide")
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Le titre du jeu doit au minimum faire {{ limit }} caractères !",
     *      maxMessage = "Le titre du jeu ne doit pas éxéder {{ limit }} caractères !"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Le slug du titre du jeu doit au minimum faire {{ limit }} caractères !",
     *      maxMessage = "Le slug du titre du jeu ne doit pas éxéder {{ limit }} caractères !"
     * )
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message = "L'adresse du jeu ne doit pas être vide")
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "L'adresse du jeu doit au minimum faire {{ limit }} caractères !",
     *      maxMessage = "L'adresse du jeu ne doit pas éxéder {{ limit }} caractères !"
     * )
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=5)
     * @Assert\NotBlank(message = "Le code postal du jeu ne doit pas être vide")
     * @Assert\Length(
     *      min=5,
     *      max=5,
     *      minMessage = "Le code postal du jeu doit au minimum faire {{ limit }} caractères !",
     *      maxMessage = "Le code postal du jeu ne doit pas éxéder {{ limit }} caractères !"
     * )
     * @Assert\Regex(pattern="/\d+/", message="Le {{ label }} ne doit être que des chiffres !")
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message = "La ville du jeu ne doit pas être vide")
     * @Assert\Length(
     *      min = 2,
     *      max = 100,
     *      minMessage = "La ville du jeu doit au minimum faire {{ limit }} caractères !",
     *      maxMessage = "La ville du jeu ne doit pas éxéder {{ limit }} caractères !"
     * )
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\Type(
     *     type="bool",
     *     message="La valeur {{ value }} n'est pas du type : {{ type }}."
     * )
     */
    private $status;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\NotBlank(message = "La date de création du jeu doit être renseignée")
     * @Assert\Type(type="\DateTimeInterface", message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Assert\Type(type="\DateTimeInterface", message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Instance::class, mappedBy="game")
     * @ORM\OrderBy({"startAt" = "DESC"})
     */
    private $instances;

    /**
     * @ORM\OneToMany(targetEntity=Checkpoint::class, mappedBy="game")
     * @ORM\OrderBy({"orderCheckpoint" = "ASC"})
     */
    private $checkpoints;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="games")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\Type(
     *     type="bool",
     *     message="La valeur {{ value }} n'est pas du type : {{ type }}."
     * )
     */
    private $isTrashed;

    public function __construct()
    {
        $this->instances = new ArrayCollection();
        $this->checkpoints = new ArrayCollection();
        $this->isTrashed = false;
        $this->status = true;
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getImage(): ?string
    {   
        if ($this->image) {
            return $this->image;
        } else {
            return 'default/game-default-image.jpg';
        }
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Instance>
     */
    public function getInstances(): Collection
    {
        return $this->instances;
    }

    /**
     * @return Collection<int, Instance>
     */
    public function getUnTrashedInstances(): Collection
    {
        $criteria = Criteria::create()
        ->andWhere(Criteria::expr()->eq('isTrashed', false));
        return $this->instances->matching($criteria);
    }

    public function addInstance(Instance $instance): self
    {
        if (!$this->instances->contains($instance)) {
            $this->instances[] = $instance;
            $instance->setGame($this);
        }

        return $this;
    }

    public function removeInstance(Instance $instance): self
    {
        if ($this->instances->removeElement($instance)) {
            // set the owning side to null (unless already changed)
            if ($instance->getGame() === $this) {
                $instance->setGame(null);
            }
        }

        return $this;
    }

    public function getNextInstance(): Instance
    {
        $date = new DateTime();
        $date = $date->getTimestamp();

        $criteria = Criteria::create()
        ->andWhere(Criteria::expr()->eq('isTrashed', false));
        $instances = $this->instances->matching($criteria);

        $instances = array_reverse($instances->toArray());
            
        foreach($instances AS $instance)
        {
            if($date >= $instance->getStartAt()->getTimestamp() && $date <= $instance->getEndAt()->getTimestamp())
            {
                return $instance;
            }
        }

        $instance_return = new Instance();
        foreach($this->instances AS $instance)
        {
            if($date < $instance->getStartAt()->getTimestamp())
            {
                $instance_return = $instance;
            }
        }

        return $instance_return;
    }

    /**
     * @return Collection<int, Checkpoint>
     */
    public function getCheckpoints(): Collection
    {
        return $this->checkpoints;
    }

    /**
     * @return Collection<int, Checkpoint>
     */
    public function getUnTrashedCheckpoints(): Collection
    {
        $criteria = Criteria::create()
        ->andWhere(Criteria::expr()->eq('isTrashed', false));
        return $this->checkpoints->matching($criteria);
    }

    public function addCheckpoint(Checkpoint $checkpoint): self
    {
        if (!$this->checkpoints->contains($checkpoint)) {
            $this->checkpoints[] = $checkpoint;
            $checkpoint->setGame($this);
        }

        return $this;
    }

    public function removeCheckpoint(Checkpoint $checkpoint): self
    {
        if ($this->checkpoints->removeElement($checkpoint)) {
            // set the owning side to null (unless already changed)
            if ($checkpoint->getGame() === $this) {
                $checkpoint->setGame(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */

templates/backoffice/game/_delete_form.html.twig
{% if is_granted('ROLE_ORGANISATEUR') %}

<form method="post" action="{{ path('app_backoffice_game_delete', {'id': game.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer le jeu {{game.title}} ?\nSes checkpoints / questions seront mis à la poubelle !');" class="mb-2">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ game.id) }}">
    <button title="Supprimer" class="btn btn-danger btn-sm me-2 mb-3"><i class="display-6 bi bi-trash"></i></button>
</form>

{% endif %}

templates/backoffice/game/_game_card.html.twig
<div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="{{delay[counter]~'s'}}">
    <div class="service-item">
        <div class="overflow-hidden align-img">
            <img  class="img-fluid" src="{{ asset(app_games_images_directory~game.image) }}" class="card-img-top" alt="{{game.slug}}" >
        </div>
        <div class="p-4 text-center border border-5 border-light border-top-0">
            <h4>{{ game.title }}
                {% if is_granted('ROLE_ADMIN') %}
                    <i>(créé par {{ (game.user.pseudo) }})</i>
                {% endif %}
            </h4>
            <div class="small mb-5">
                <address class="mb-0">{{ game.city }} ({{ game.postalCode }})</address>
            </div>
            
                <div class="d-flex justify-content-evenly">
                    <a title="Voir" href="{{ path('app_backoffice_game_show', {'slug': game.slug}) }}" class="btn btn-primary btn-sm me-2 mb-4"><i class="display-6 bi bi-eye"></i></a>
                    {{ include('backoffice/game/_status_form.html.twig', {"method": ''}) }}
                    {{ include('backoffice/game/_delete_form.html.twig', {"method": ''}) }}
                </div>
            
        </div>
    </div>
</div>

templates/backoffice/game/_status_form.html.twig
<form method="post" action="{{ path('app_backoffice_update_status', {'id': game.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir {% if game.status is same as false %}activer{% else %}désactiver{% endif %} le jeu {{game.title}} ?');" class="mb-2">
    <input type="hidden" name="_token" value="{{ csrf_token('trash' ~ game.id) }}">
    <button title="Activer / Désactiver" class="btn btn-outline-dark btn-sm me-2 mb-3">{% if game.status is same as false %} <i class="display-6 bi bi-lightbulb"></i> {% else %} <i class="display-6 bi bi-lightbulb-off"></i> {% endif %}</button>
</form>

templates/backoffice/game/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ game.title }}{% endblock %}

{% block body %}

{{ include('_header_start.html.twig', {'title': game.title}) }}

<!-- Feature Start -->
<div class="container-fluid bg-light px-lg-0" style="margin: 3rem 0;">
    <div class="container feature px-lg-0">
        <div class="row g-0 mx-lg-0">
            <div class="col-lg-6 feature-text py-5 wow fadeIn" data-wow-delay="0.5s">
                <div class="p-lg-5 ps-lg-0">
                    <div class="section-title text-start">
                        <h1 class="display-5 mb-4">{{ game.title }}</h1>
                    </div>
                        <p class="mb-2 pb-2">{{ game.summary | nl2br }}</p>
                        <p class="mb-4 pb-2"><small class="text-muted">Lieu: {{ game.address }} - {{ game.postalCode }} {{ game.city }}</small></p>
 
                    <div class="d-flex justify-content-start">
                        <a title="Modifier" href="{{ path('app_backoffice_game_edit',{'slug': game.slug}) }}" class="btn btn-warning btn-sm me-2 mb-4"><i class="display-6 bi bi-pencil"></i></a>
                        {{ include('backoffice/game/_status_form.html.twig', {"method": 'show'}) }}
                        {{ include('backoffice/game/_delete_form.html.twig', {"method": 'show'}) }}
                    </div>

                </div>
            </div>
            <div class="col-lg-6 pe-lg-0" style="min-height: 400px;">
                <div class="position-relative h-100 d-flex align-items-center">
                    <img class="position-absolute img-fluid w-100" src="{{ asset(app_games_images_directory~game.image) }}" style="object-fit: cover;    max-height: 100%;" alt="{{ game.slug }}">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Feature End -->

{# GAME INSTANCES AND CHECKPOINTS #}

<div id="games-cards-ic" class="d-flex bd-highlight mx-3">
    {# INSTANCES #}
    <div class="card mb-3 flex-grow-1" style="flex-basis:min-content;" >
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <h2 class="p-2 align-self-center flex-grow-1">Les sessions</h2>
            <a class="btn btn-primary m-3" href="{{ path('app_backoffice_instance_new', {'gameSlug': game.slug}) }}">Créer une session</a>
        </div>
        <div class="accordion" id="ac-instances">
            {% for instance in instances %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="instance-head-{{loop.index}}">
                        <button class="accordion-button text-white bg-gradient
                        {% if "now"|date('c') > instance.startAt|date('c') and "now"|date('c') > instance.endAt|date('c') %} 
                            bg-secondary  
                            {% set libelle_instance = "Terminée" %}
                        {% elseif "now"|date('c') > instance.startAt|date('c') and "now"|date('c') < instance.endAt|date('c') %} 
                            bg-success  
                            {% set libelle_instance = "En cours" %}
                        {% else %}
                            bg-primary
                            {% set libelle_instance = "A venir" %}
                        {% endif %}
                        collapsed" 
                        
                        type="button" data-bs-toggle="collapse" data-bs-target="#instances-{{loop.index}}" 
                        
                            aria-expanded="false" 
                        aria-controls="instances-{{loop.index}}">
                            {{libelle_instance}} : {{ instance.title }} , du {{instance.startAt|format_datetime(pattern="dd LLLL Y", locale='fr')}} à {{instance.startAt|date('H:i')}} au {{instance.endAt|format_datetime(pattern="dd LLLL Y", locale='fr')}} à {{instance.endAt|date('H:i')}}
                        </button>
                    </h2>
                    <div id="instances-{{loop.index}}" class="accordion-collapse collapse" aria-labelledby="instance-head-{{loop.index}}" data-bs-parent="#ac-instances">
                        <div class="accordion-body">
                            <div class="mb-3">
                                <strong>{{instance.message | nl2br}}</strong>
                            </div>
                            <div class="d-flex bd-highlight align-items-start">
                                {% if "now"|date('c') > instance.startAt|date('c') and "now"|date('c') < instance.endAt|date('c') %}
                                    <a href="{{ path('app_front_instance_realtime', {'gameSlug': instance.game.slug, 'instanceSlug': instance.slug}) }}" class="btn btn-primary btn-sm me-3">Voir les positions des joueurs</a>
                                {% else %}
                                <a href="{{ path('app_backoffice_instance_score', {'instanceSlug' : instance.slug}) }}" class="btn btn-primary btn-sm me-3">Voir les scores</a>
                                {% endif %}
                                <a href="{{ path('app_backoffice_instance_edit',{'instanceSlug': instance.slug}) }}" class="btn btn-warning btn-sm me-3">Modifier</a>
                                {{ include('backoffice/instance/_delete_form.html.twig') }}
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </div>
    </div>
    {# CHECKPOINTS #}
    <div class="card mb-3 flex-grow-1"  style="flex-basis:min-content;">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <h2 class="p-2 align-self-center flex-grow-1">Les checkpoints</h2>
            <a class="btn btn-warning m-3" href="{{ path('app_backoffice_game_pdf', { 'slug' : game.slug}) }}" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filetype-pdf" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM1.6 11.85H0v3.999h.791v-1.342h.803c.287 0 .531-.057.732-.173.203-.117.358-.275.463-.474a1.42 1.42 0 0 0 .161-.677c0-.25-.053-.476-.158-.677a1.176 1.176 0 0 0-.46-.477c-.2-.12-.443-.179-.732-.179Zm.545 1.333a.795.795 0 0 1-.085.38.574.574 0 0 1-.238.241.794.794 0 0 1-.375.082H.788V12.48h.66c.218 0 .389.06.512.181.123.122.185.296.185.522Zm1.217-1.333v3.999h1.46c.401 0 .734-.08.998-.237a1.45 1.45 0 0 0 .595-.689c.13-.3.196-.662.196-1.084 0-.42-.065-.778-.196-1.075a1.426 1.426 0 0 0-.589-.68c-.264-.156-.599-.234-1.005-.234H3.362Zm.791.645h.563c.248 0 .45.05.609.152a.89.89 0 0 1 .354.454c.079.201.118.452.118.753a2.3 2.3 0 0 1-.068.592 1.14 1.14 0 0 1-.196.422.8.8 0 0 1-.334.252 1.298 1.298 0 0 1-.483.082h-.563v-2.707Zm3.743 1.763v1.591h-.79V11.85h2.548v.653H7.896v1.117h1.606v.638H7.896Z"/>
                        </svg> Générer le PDF des checkpoints</a>
            <a class="btn btn-primary m-3" href="{{ path('app_backoffice_checkpoint_new', { 'gameSlug' : game.slug}) }}">Créer un checkpoint</a>
        </div>
        <div class="accordion" id="ac-checkpoints">
            {% for checkpoint in game.unTrashedCheckpoints %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="checkpoint-head-{{loop.index}}">
                        <button class="accordion-button text-white bg-gradient collapsed bg-dark"                                 
                        type="button" data-bs-toggle="collapse" data-bs-target="#checkpoints-{{loop.index}}" 
                        aria-expanded="false" 
                        aria-controls="checkpoints-{{loop.index}}">
                            {{checkpoint.title}}
                        </button>
                    </h2>
                    <div id="checkpoints-{{loop.index}}" class="accordion-collapse collapse" aria-labelledby="checkpoint-head-{{loop.index}}" data-bs-parent="#ac-checkpoints">
                        <div class="accordion-body">
                            <div class="mb-3">
                                <strong>{{checkpoint.successMessage | nl2br}}</strong>
                            </div>
                            <div class="d-flex bd-highlight align-items-start">
                                <a href="{{ path('app_backoffice_checkpoint_show', {'id': checkpoint.id}) }}" class="btn btn-primary btn-sm me-3">Voir</a>
                                {% if checkpoint.unTrashedEnigmas|length == 0 %}
                                    <a class="btn btn-primary btn-sm me-3" href="{{ path('app_backoffice_enigma_new', {'id': checkpoint.id}) }}">Créer une énigme</a>
                                {% endif %}
                                <a href="{{ path('app_backoffice_checkpoint_edit',{'id': checkpoint.id}) }}" class="btn btn-warning btn-sm me-3">Modifier</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}