src/Entity/Round.php
<?php

namespace App\Entity;

use App\Repository\RoundRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RoundRepository::class)
 */
class Round
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\NotBlank(message = "La date de début du round doit être renseignée")
     * @Assert\DateTime(message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $startAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Assert\DateTime(message = "La date {{value}} du champ {{label}} n'est pas au bon format")
     */
    private $endAt;

    /**
     * @ORM\ManyToOne(targetEntity=Instance::class, inversedBy="rounds")
     * @ORM\JoinColumn(nullable=false)
     */
    private $instance;

    /**
     * @ORM\OneToMany(targetEntity=ScanQR::class, mappedBy="round")
     * @ORM\OrderBy({"scanAt" = "DESC"})
     */
    private $scanQRs;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="rounds")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=UserAnswer::class, mappedBy="round")
     */
    private $userAnswers;

    public function __construct()
    {
        $this->scanQRs = new ArrayCollection();
        $this->userAnswers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(?\DateTimeImmutable $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function getInstance(): ?Instance
    {
        return $this->instance;
    }

    public function setInstance(?Instance $instance): self
    {
        $this->instance = $instance;

        return $this;
    }

    /**
     * @return Collection<int, ScanQR>
     */
    public function getScanQRs(): Collection
    {
        return $this->scanQRs;
    }

    public function addScanQR(ScanQR $scanQR): self
    {
        if (!$this->scanQRs->contains($scanQR)) {
            $this->scanQRs[] = $scanQR;
            $scanQR->setRound($this);
        }

        return $this;
    }

    public function removeScanQR(ScanQR $scanQR): self
    {
        if ($this->scanQRs->removeElement($scanQR)) {
            // set the owning side to null (unless already changed)
            if ($scanQR->getRound() === $this) {
                $scanQR->setRound(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLastScanAt()
    {
        $scanQRs = $this->scanQRs;
        return $scanQRs[0];
    }

    /**
     * @return Collection<int, UserAnswer>
     */
    public function getUserAnswers(): Collection
    {
        return $this->userAnswers;
    }

    public function addUserAnswer(UserAnswer $userAnswer): self
    {
        if (!$this->userAnswers->contains($userAnswer)) {
            $this->userAnswers[] = $userAnswer;
            $userAnswer->setRound($this);
        }

        return $this;
    }

    public function removeUserAnswer(UserAnswer $userAnswer): self
    {
        if ($this->userAnswers->removeElement($userAnswer)) {
            // set the owning side to null (unless already changed)
            if ($userAnswer->getRound() === $this) {
                $userAnswer->setRound(null);
            }
        }

        return $this;
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Service\CascadeTrashed;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * @Route("/admin/user", name="app_admin_user_")
 * @IsGranted("ROLE_ADMIN") 
 */
class UserController extends AbstractController
{
    private $paramBag;

    public function __construct(ParameterBagInterface $paramBag)
    {
        $this->paramBag = $paramBag;
    }

    /**
     * @Route("/", name="index", methods={"GET"})
     */
    public function index(UserRepository $userRepository, Request $request): Response
    {
        $limit_user_per_page = $this->paramBag->get('app.limit_users_per_page');
        $current_page = $request->query->get('page') ? $request->query->get('page') : 1;
        
        $users = $userRepository->findBy([], ['email' => 'ASC'], $limit_user_per_page, ($current_page-1)*$limit_user_per_page);

        return $this->render('admin/user/index.html.twig', [
            'users' => $users,
            "pages" => ceil(count($userRepository->findAll())/$limit_user_per_page)
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword($passwordHasher->hashPassword($user, $user->getPassword()));
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash(
                'notice-success',
                'L\'utilisateur '.$user->getEmail().' a été ajouté !'
            );

            return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     */
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('password')->getData() !== null) {
                $user->setPassword($passwordHasher->hashPassword($user, $form->get('password')->getData()));
            }
            $entityManager->flush();

            $this->addFlash(
                'notice-success',
                'L\'utilisateur '.$user->getEmail().' a été modifié !'
            );

            return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/status/{id}",name="update_status", methods={"POST"}, requirements={"id"="\d+"})
     *
     * @param User $user
     * @return void
     */
    public function update_status(Request $request, User $user, EntityManagerInterface $entityManager, CascadeTrashed $cascadeTrashed)
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            if ($user->getStatus()) {
                foreach ($user->getGames() as $game) {
                    $cascadeTrashed->trashGame($game);
                }
                $user->setStatus(false);
                $this->addFlash(
                    'notice-success',
                    'L\'utilisateur '.$user->getEmail().' a été désactivé ! Tous ses jeux, checkpoints, questions et instances ont été mis à la poubelle !'
                );
            } else {
                $user->setStatus(true);
                $this->addFlash(
                    'notice-success',
                    'L\'utilisateur '.$user->getEmail().' a été activé !'
                );
            }

            $entityManager->flush();
        }
        else
        {
            $this->addFlash(
                'notice-danger',
                'Impossible de désactiver l\'utilisateur '.$user->getEmail().', token invalide !'
            );
        }
        return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/GameController.php
<?php

namespace App\Controller\Front;

use App\Entity\Game;
use App\Entity\Instance;
use App\Repository\GameRepository;
use App\Repository\InstanceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @Route("/jeux",name="front_")
 */
class GameController extends AbstractController
{
    private $paramBag;
    private $urlGenerator;
    private $breadcrumb;

    public function __construct(ParameterBagInterface $paramBag, UrlGeneratorInterface $urlGenerator)
    {
        $this->paramBag = $paramBag;
        $this->urlGenerator = $urlGenerator;
        $this->breadcrumb = array(array('libelle' => 'Accueil', 'libelle_url' => 'front_main', 'url' => $this->urlGenerator->generate('front_main')));
    }
    /**
     * @Route("/", name="games", methods={"GET"})
     */
    public function index(GameRepository $gameRepository, Request $request): Response
    {
        $limit_games_per_page = $this->paramBag->get('app.limit_games_per_page');
        $current_page = $request->query->get('page') ? $request->query->get('page') : 1;
        
        $games = $gameRepository->findBy(['isTrashed' => 0, 'status' => 1], ['createdAt' => 'DESC'], $limit_games_per_page, ($current_page-1)*$limit_games_per_page);

        array_push($this->breadcrumb, array('libelle' => 'Les jeux', 'libelle_url' => 'front_games', 'url' => $this->urlGenerator->generate('front_games')));

        return $this->render('front/game/index.html.twig', [
            'games' => $games,
            "pages" => ceil(count($gameRepository->findBy(['isTrashed' => 0, 'status' => 1]))/$limit_games_per_page),
            'breadcrumbs' => $this->breadcrumb,
        ]);
    }

    /**
     * @Route("/{slug}",name="games_show", methods={"GET"})
     *
     * @return Response
     */
    public function show(Game $game): Response
    {
        /* This is a method of the Game entity that returns all the instances of the game that are not
        trashed. */
        $instances = $game->getUnTrashedInstances();
        /* This is a method of the Instance entity that returns all the instances that are not trashed
        and that are not finished. */
        $next_instances = $instances->filter(function(Instance $instance){
            return $instance->getEndAt() > new \DateTimeImmutable();
        });
        /* This is a method of the Instance entity that returns all the instances that are not trashed
        and that are finished. */
        $previous_instances = $instances->filter(function(Instance $instance){
            return $instance->getEndAt() <= new \DateTimeImmutable();
        });

        array_push($this->breadcrumb, array('libelle' => 'Les jeux', 'libelle_url' => 'front_games', 'url' => $this->urlGenerator->generate('front_games')));
        array_push($this->breadcrumb, array('libelle' => $game->getTitle(), 'libelle_url' => 'front_games_show', 'url' => $this->urlGenerator->generate('front_games_show', ['slug' => $game->getSlug()])));

        return $this->render('front/game/show.html.twig', [
            'game' => $game,
            'next_instances' => $next_instances,
            'previous_instances' => $previous_instances,
            'breadcrumbs' => $this->breadcrumb,
        ]);
    }
}

src/Controller/Front/UserController.php
<?php

namespace App\Controller\Front;

use App\Entity\Game;
use App\Entity\Round;
use App\Form\UserType;
use App\Entity\Instance;
use App\Form\RegistrationFormType;
use App\Repository\GameRepository;
use App\Repository\UserRepository;
use App\Repository\RoundRepository;
use App\Repository\InstanceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * @Route("/user/",name="app_front_user_")
 */
class UserController extends AbstractController
{
    /**
     * @Route("profil", name="profile", methods={"GET", "POST"})
     */
    public function profile(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher, RoundRepository $roundRepository, ParameterBagInterface $paramBag)
    {
        $user = $this->getUser();

        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('password')->getData() !== null) {
                $user->setPassword($passwordHasher->hashPassword($user, $form->get('password')->getData()));
            }

            $file = $form['image']->getData();
            if($file !== null)
            {
                $pseudo = $user->getPseudo();
                $id = $user->getId();
                $filename = $pseudo.'-'. $id.'.'.$file->guessExtension();
                $file->move($paramBag->get('app.profile_images_directory'), $filename);
                $user->setImage($filename);
            }

            $entityManager->flush();

            $this->addFlash(
                'notice-success',
                'Votre profil a été mis à jour !'
            );

            return $this->redirectToRoute('app_front_user_profile', [], Response::HTTP_SEE_OTHER);
        }
        
        // It's getting the user id of the user connected.
        $userConnected = $this->getUser()->getId();
        $rounds = $roundRepository->findBy(['user' => $userConnected], ['endAt' => 'ASC']);

        return $this->renderForm('front/user/profile.html.twig', [
            'user' => $user,
            'form' => $form,
            'rounds' => $rounds,
        ]);
    }

}

templates/front/user/_game_card.html.twig
{% set delay = [0.1, 0.3, 0.5] %}
    <div class="container-xxl py-5">
        <div class="container">
        <h2>Mes parties</h2> 
            <div class="row g-4">
            {% for round in rounds %}                
                {% set counter = ( counter | default(-1) ) + 1 %}
                {% if counter == 3 %}
                    {% set counter = 0 %}
                {% endif %}

                <div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="{{delay[counter]~'s'}}">
                    <div class="service-item">
                        <div class="overflow-hidden align-img">
                            <img class="img-fluid" src="{{ asset(app_games_images_directory~round.instance.game.image) }}" alt="{{round.instance.game.slug}}">
                        </div>
                        <div class="p-4 text-center border border-5 border-light border-top-0">

                            <h4><a class="fw-medium" href="{{ path('app_front_instance_show', {'gameSlug': round.instance.game.slug , 'instanceSlug': round.instance.slug}) }}">{{ round.instance.title }}</a></h4>
                    
                                {% if round.endAt is same as null and "now"|date('c') > round.instance.startAt|date('c') and "now"|date('c') < round.instance.endAt|date('c') and round.endAt is same as null %}
                                    <span class="badge bg-danger ms-2">Session en cours</span>
                                {% endif %}

                                {% if round.endAt is not same as null %}
                                    <div class="small mb-3">
                                        <address class="mb-0">
                                            <p class="card-text">La partie s'est finie le {{ round.endAt|format_datetime(pattern="dd LLLL Y", locale='fr')}}, à {{ round.instance.game.city }} ({{ round.instance.game.postalCode }}).</p>
                                            <p> <b>Tu as fini le jeu en {{ round.endAt.diff(round.startAt)|date("%Hh%Imin%Ssec") }} </b></p>
                                        </address>
                                    </div>
                                    <a class="fw-medium" href="{{ path('app_front_instance_score', {'gameSlug': round.instance.game.slug , 'instanceSlug': round.instance.slug}) }}">Voir le classement<i class="fa fa-arrow-right ms-2"></i></a>
                                {% elseif "now"|date('c') > round.instance.startAt|date('c') and "now"|date('c') < round.instance.endAt|date('c') and round.endAt is same as null %}
                                    <div class="small mb-3">
                                        <address class="mb-0">
                                            <p class="card-text">La partie est en cours, tu n'as pas encore terminé, tu peux revoir ton dernier indice <a href="{{ path('front_checkpoint_check', {'id': round.lastScanAt.checkpoint.id , 'token': round.lastScanAt.checkpoint.title | sha1 }) }}">ici</a></p>
                                        </address>
                                    </div>
                                    <p>{{ round.instance.game.summary|u.truncate(80, '...', false)}}</p>
                                    <a class="fw-medium" href="{{ path('app_front_instance_realtime', {'gameSlug': round.instance.game.slug , 'instanceSlug': round.instance.slug}) }}">Voir le classement<i class="fa fa-arrow-right ms-2"></i></a>
                                {% elseif "now"|date('c') > round.instance.endAt|date('c') and round.endAt is same as null %}
                                    <div class="small mb-3">
                                        <address class="mb-0">
                                            <p class="card-text">La partie est terminée, malheureusement tu n'es pas allé jusqu'au bout</p>
                                        </address>
                                    </div>
                                    <p>{{ round.instance.game.summary}}</p>
                                    <a class="fw-medium" href="{{ path('app_front_instance_score', {'gameSlug': round.instance.game.slug , 'instanceSlug': round.instance.slug}) }}">Voir le classement<i class="fa fa-arrow-right ms-2"></i></a>
                                {% endif %}
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="d-flex align-items-center p-2 bd-highlight">Vous n'avez pas encore joué !</div>
            {% endfor %}
            </div>
            {{ include('_paginate.html.twig') }}
        </div>
    </div>

templates/front/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block body %}
    {{ include('_header_start.html.twig', {'title': 'Votre profil'}) }}
    <div class="d-flex flex-column" >
        <div class="d-flex mobile-profile">
        {% if user.image is same as null %}
            <div>
                <img src="{{ asset(app_profile_images_directory~'default.png') }}" class="img-profile" alt="default" >
            </div>
        {% else %}
            <div>
                <img src="{{ asset(app_profile_images_directory~user.image) }}" class="img-profile" alt="{{ user.image }}" >
            </div>
        {% endif %}
            <div class="col-xl-6 text-center">
                {{ form_start(form) }}
                    <div class="form-error mb-3">
                        {{ form_errors(form.image) }}
                        {{ form_errors(form.password) }}
                        {{ form_errors(form.pseudo) }}
                        {{ form_errors(form.lastname) }}
                        {{ form_errors(form.firstname) }}
                        {% if is_granted('ROLE_ORGANISATEUR') %}
                            {{ form_errors(form.address) }}
                            {{ form_errors(form.postalCode) }}
                            {{ form_errors(form.city) }}
                        {% endif %}
                    </div>

                    <div class="profile-informations">
                        <div class="profile col form-floating mb-3">
                            {{ form_widget(form.pseudo) }}
                            {{ form_label(form.pseudo) }}
                        </div>

                        <div class="profile col form-floating mb-3">
                            {{ form_widget(form.password) }}
                            {{ form_label(form.password) }}
                        </div>
                    </div>

                    <div class="profile-informations">
                        <div class="profile col form-floating mb-3">
                            {{ form_widget(form.lastname) }}
                            {{ form_label(form.lastname) }}
                        </div>

                        <div class="profile col form-floating mb-3">
                            {{ form_widget(form.firstname) }}
                            {{ form_label(form.firstname) }}
                        </div>
                    </div>
                    <div class="col form-floating mb-3">
                        {{ form_widget(form.image) }}
                        {{ form_label(form.image) }}
                    </div>

                    {% if is_granted('ROLE_ORGANISATEUR') %}
                        <div class="form-floating mb-3">
                            {{ form_widget(form.address) }}
                            {{ form_label(form.address) }}
                        </div>

                        <div class="form-floating mb-3">
                            {{ form_widget(form.postalCode) }}
                            {{ form_label(form.postalCode) }}
                        </div>

                        <div class="form-floating mb-3">
                            {{ form_widget(form.city) }}
                            {{ form_label(form.city) }}
                        </div>
                    {% endif %}
                        
                    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>

{# {% if next_rounds is not empty %}
    {{ include ('front/user/_instance_card.html.twig', {"roundss": next_rounds|reverse, "title": "Prochaines sessions de jeu", "label": "next"} ) }}
{% endif %}

{% if previous_rounds is not empty %}
    {{ include ('front/user/_instance_card.html.twig', {"roundss": previous_rounds, "title": "Anciennes sessions de jeu", "label": "prev"} ) }}
{% endif %} #}
    {{ include('front/user/_game_card.html.twig') }}
</div>

{% endblock %}